# .golangci.yml
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true
  gocritic:
    enabled-checks:
      - appendAssign
      - sloppyLen
      - hugeParam
      - rangeValCopy
  govet:
    check-shadowing: true
