// Package sqlite provides a SQLite implementation of outbox.Store using
// database/sql. Use it with any SQLite database/sql driver (mattn/go-sqlite3,
// modernc.org/sqlite, etc.).
//
// SQLite has no FOR UPDATE SKIP LOCKED. FetchPending wraps the claim in a
// short transaction; concurrent workers serialize on the database write lock,
// which is fine for most outbox workloads but does not scale to many parallel
// claimers the way PostgreSQL does.
package sqlite

import (
	"context"
	stdsql "database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/enverbisevac/libs/outbox"
	osql "github.com/enverbisevac/libs/outbox/sql"
)

var _ outbox.Store = (*Store)(nil)

// Store implements outbox.Store for SQLite.
type Store struct {
	config osql.Config
	db     *stdsql.DB
}

// New creates a new SQLite outbox store backed by *sql.DB.
func New(db *stdsql.DB, options ...osql.Option) *Store {
	config := osql.DefaultConfig()
	for _, opt := range options {
		opt.Apply(&config)
	}
	return &Store{
		config: config,
		db:     db,
	}
}

// newID generates a new message id using the configured generator.
func (s *Store) newID() string { return s.config.IDGenerator() }

// Save persists messages within the given transaction.
// tx may be a *sql.Tx, or nil to have the Store create its own transaction.
// Message IDs are generated by the Store when empty.
func (s *Store) Save(ctx context.Context, tx any, msgs ...outbox.Message) error {
	query := fmt.Sprintf(
		`INSERT INTO %s (id, topic, key, payload, headers) VALUES (?, ?, ?, ?, ?)`,
		s.config.TableName,
	)

	switch t := tx.(type) {
	case *stdsql.Tx:
		return s.execInsert(ctx, t, query, msgs)
	case nil:
		return s.saveWithDB(ctx, query, msgs)
	default:
		return fmt.Errorf("outbox: unsupported tx type %T", tx)
	}
}

func (s *Store) saveWithDB(ctx context.Context, query string, msgs []outbox.Message) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("outbox: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	if err := s.execInsert(ctx, tx, query, msgs); err != nil {
		return err
	}
	return tx.Commit()
}

func (s *Store) execInsert(ctx context.Context, tx *stdsql.Tx, query string, msgs []outbox.Message) error {
	for _, msg := range msgs {
		id := msg.ID
		if id == "" {
			id = s.newID()
		}
		headers, err := json.Marshal(msg.Headers)
		if err != nil {
			return fmt.Errorf("outbox: marshal headers: %w", err)
		}
		if _, err := tx.ExecContext(ctx, query, id, msg.Topic, msg.Key, msg.Payload, headers); err != nil {
			return fmt.Errorf("outbox: save: %w", err)
		}
	}
	return nil
}

// FetchPending atomically claims up to limit pending messages for processing.
// Wrapped in a transaction so the SELECT and UPDATE see a consistent snapshot.
func (s *Store) FetchPending(ctx context.Context, limit int) ([]outbox.Message, error) {
	query := fmt.Sprintf(`UPDATE %s
SET status = 'processing'
WHERE id IN (
	SELECT id FROM %s
	WHERE status = 'pending'
	ORDER BY created_at
	LIMIT ?
)
RETURNING id, topic, key, payload, headers, status, retries, last_error, created_at, processed_at`,
		s.config.TableName, s.config.TableName)

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("outbox: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	rows, err := tx.QueryContext(ctx, query, limit)
	if err != nil {
		return nil, fmt.Errorf("outbox: fetch pending: %w", err)
	}
	msgs, scanErr := osql.ScanMessages(rows)
	_ = rows.Close()
	if scanErr != nil {
		return nil, scanErr
	}
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("outbox: commit fetch: %w", err)
	}
	return msgs, nil
}

// MarkProcessed marks messages as successfully processed.
func (s *Store) MarkProcessed(ctx context.Context, ids ...string) error {
	if len(ids) == 0 {
		return nil
	}

	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = "?"
		args[i] = id
	}

	query := fmt.Sprintf(
		`UPDATE %s SET status = 'processed', processed_at = CURRENT_TIMESTAMP WHERE id IN (%s)`,
		s.config.TableName, strings.Join(placeholders, ","),
	)

	if _, err := s.db.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("outbox: mark processed: %w", err)
	}
	return nil
}

// MarkFailed increments retries and records the error.
// Sets status to failed when max retries reached, else back to pending.
func (s *Store) MarkFailed(ctx context.Context, id string, err error) error {
	query := fmt.Sprintf(
		`UPDATE %s SET
			retries = retries + 1,
			last_error = ?,
			status = CASE WHEN retries + 1 >= ? THEN 'failed' ELSE 'pending' END
		WHERE id = ?`,
		s.config.TableName,
	)

	errMsg := ""
	if err != nil {
		errMsg = err.Error()
	}

	if _, execErr := s.db.ExecContext(ctx, query, errMsg, s.config.MaxRetries, id); execErr != nil {
		return fmt.Errorf("outbox: mark failed: %w", execErr)
	}
	return nil
}
